version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 3s
      timeout: 3s
      retries: 5

  app:
    build: .
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./incoming:/app/incoming
      - ./normalized:/app/normalized
      - ./processed:/app/processed
      - ./config:/app/config

  streamlit:
    build: .
    command: streamlit run streamlit_app.py --server.port=8501 --server.enableCORS=false
    ports:
      - "8501:8501"
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
